import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction & Purpose',
      items: [
        'web-sdk/intro',
      ],
    },
    {
      type: 'category',
      label: 'API Overview',
      items: [
        'web-sdk/api-overview/cellpay-sdk-overview',
      ],
    },
    {
      type: 'category',
      label: 'API Access, Authentication & Environments',
      items: [
        'web-sdk/api-access-authentication-and-environments/api-access-and-environment-urls',
        'web-sdk/api-access-authentication-and-environments/authentication-mechanism',
      ],
    },
    {
      type: 'category',
      label: 'SDK Payment Processing Architecture',
      items: [
        'web-sdk/sdk-payment-processing-architecture/architecture-overview',
        'web-sdk/sdk-payment-processing-architecture/sdk-payment-processing-architecture',
        'web-sdk/sdk-payment-processing-architecture/sdk-payment-flow-overview',
        'web-sdk/sdk-payment-processing-architecture/summery-of-sdk-workflow',
      ],
    },
    {
      type: 'category',
      label: 'SDK Integration & Session Management',
      items: [
        'web-sdk/sdk-integration-and-session-management/sdk-overview',
        'web-sdk/sdk-integration-and-session-management/access-token-retrieval',
      ],
    },
    {
      type: 'category',
      label: 'Payment Session Initialization API',
      items: [
        'web-sdk/payment-session-initialization-api/overview',
        'web-sdk/payment-session-initialization-api/encrypted-request-structure',
        'web-sdk/payment-session-initialization-api/plain-data-payload',
        'web-sdk/payment-session-initialization-api/generate-signature',
        'web-sdk/payment-session-initialization-api/transaction-status-inquiry',
        'web-sdk/payment-session-initialization-api/status-code',
      ],
    },
    {
      type: 'category',
      label: 'Development Code & Examples',
      items: [
        'web-sdk/development-code-and-examples/creating-payment-request-dto',
        'web-sdk/development-code-and-examples/cryptography-java',
        'web-sdk/development-code-and-examples/load-public-and-private-key',
        'web-sdk/development-code-and-examples/sign-using-private-key',
        'web-sdk/development-code-and-examples/generate-secret-aes-key',
        'web-sdk/development-code-and-examples/random-string-generator',
        'web-sdk/development-code-and-examples/encrypt-secret-key-with-rsa',
        'web-sdk/development-code-and-examples/encrypt-payload-with-rsa',
      ],
    },
    {
      type: 'category',
      label: 'Sample Requests & Responses',
      items: [
        'web-sdk/sample-requests-and-responses/payment-request-raw-request',
        'web-sdk/sample-requests-and-responses/sample-success-html-response',
      ],
    },
    {
      type: 'category',
      label: 'Web User Interfaces',
      items: [
        'web-sdk/web-user-interfaces/customer-login-page',
      ],
    },
    "web-sdk/change-log"
  ],

};

export default sidebars;
